site_name: ReViewPoint
site_description: Documentation and development manual for ReViewPoint. Modular, scalable, and LLM-powered platform for scientific paper review.
site_author: ReViewPoint Team
site_url: https://github.com/filip-herceg/ReViewPoint

docs_dir: content

nav:
  - Home: index.md
  - Quickstart:
      - Setup Guide: setup.md
      - System Architecture: architecture.md
      - FAQ: faq.md
  - Development:
      - Developer Guidelines: dev-guidelines.md
      - CI/CD: ci-cd.md
      - Changelog: changelog.md
      - Contributing to Documentation: contributing-docs.md
      - How to Use the Docs: how-to-use-docs.md
      - Documentation Enhancements: documentation-enhancements.md
  - Backend:
      - Backend Source Guide: backend-source-guide.md
      - API Reference: api-reference.md
      - Backend API Reference: backend/api-reference.md
      - Backend Source:
          - Overview: backend/src/__init__.py.md
          - Main Application: backend/src/main.py.md
          - About: backend/src/__about__.py.md
          - API Package: backend/src/api/__init__.py.md
          - API Dependencies: backend/src/api/deps.py.md
          - API v1 Overview: backend/src/api/v1/__init__.py.md
          - API v1 Authentication: backend/src/api/v1/auth.py.md
          - API v1 Health Check: backend/src/api/v1/health.py.md
          - API v1 File Uploads: backend/src/api/v1/uploads.py.md
          - API v1 WebSocket: backend/src/api/v1/websocket.py.md
          - API v1 Users Overview: backend/src/api/v1/users/__init__.py.md
          - API v1 Users Core: backend/src/api/v1/users/core.py.md
          - API v1 Users Exports: backend/src/api/v1/users/exports.py.md
          - API v1 Users Test Router: backend/src/api/v1/users/test_only_router.py.md
          - Core Package: backend/src/core/__init__.py.md
          - Core Configuration: backend/src/core/config.py.md
          - Core Database: backend/src/core/database.py.md
          - Core Sync Database: backend/src/core/sync_database.py.md
          - Core Documentation: backend/src/core/documentation.py.md
          - Core Events: backend/src/core/events.py.md
          - Core Feature Flags: backend/src/core/feature_flags.py.md
          - Core Logging: backend/src/core/logging.py.md
          - Core OpenAPI: backend/src/core/openapi.py.md
          - Core Security: backend/src/core/security.py.md
          - Core JOSE Types: backend/src/core/typings/jose.pyi.md
          - Models Package: backend/src/models/__init__.py.md
          - Models Base Model: backend/src/models/base.py.md
          - Models User Model: backend/src/models/user.py.md
          - Models File Model: backend/src/models/file.py.md
          - Models Blacklisted Token: backend/src/models/blacklisted_token.py.md
          - Models Used Password Reset Token: backend/src/models/used_password_reset_token.py.md
          - Services Package: backend/src/services/__init__.py.md
          - Services User Service: backend/src/services/user.py.md
          - Services Upload Service: backend/src/services/upload.py.md
          - Repositories Package: backend/src/repositories/__init__.py.md
          - Repositories User Repository: backend/src/repositories/user.py.md
          - Repositories File Repository: backend/src/repositories/file.py.md
          - Repositories Blacklisted Token Repository: backend/src/repositories/blacklisted_token.py.md
          - Schemas Package: backend/src/schemas/__init__.py.md
          - Schemas Authentication Schemas: backend/src/schemas/auth.py.md
          - Schemas User Schemas: backend/src/schemas/user.py.md
          - Schemas File Schemas: backend/src/schemas/file.py.md
          - Schemas Token Schemas: backend/src/schemas/token.py.md
          - Schemas Blacklisted Token Schemas: backend/src/schemas/blacklisted_token.py.md
          - Utils Package: backend/src/utils/__init__.py.md
          - Utils Cache Utilities: backend/src/utils/cache.py.md
          - Utils DateTime Utilities: backend/src/utils/datetime.py.md
          - Utils Environment Utilities: backend/src/utils/environment.py.md
          - Utils Error Utilities: backend/src/utils/errors.py.md
          - Utils File Utilities: backend/src/utils/file.py.md
          - Utils Filter Utilities: backend/src/utils/filters.py.md
          - Utils Hashing Utilities: backend/src/utils/hashing.py.md
          - Utils HTTP Error Utilities: backend/src/utils/http_error.py.md
          - Utils Rate Limit Utilities: backend/src/utils/rate_limit.py.md
          - Utils Validation Utilities: backend/src/utils/validation.py.md
          - Middlewares Package: backend/src/middlewares/__init__.py.md
          - Middlewares Logging Middleware: backend/src/middlewares/logging.py.md
          - Alembic Migrations: backend/src/alembic_migrations/__init__.py.md
          - Alembic Configuration: backend/src/alembic_migrations/alembic.ini.md
          - Alembic Environment: backend/src/alembic_migrations/env.py.md
          - Alembic Script Template: backend/src/alembic_migrations/script.py.mako.md
          - Alembic README: backend/src/alembic_migrations/README.md
          - Migration Initial Migration: backend/src/alembic_migrations/versions/initial_migration.md
          - Migration Initial Migration (Python): backend/src/alembic_migrations/versions/f140e6f46727_initial_migration.py.md
          - Migration Users and Files Tables: backend/src/alembic_migrations/versions/9fc3acc47815_initial_migration_users_and_files_tables.md
          - Migration Add File Size Field: backend/src/alembic_migrations/versions/31eb30e5f037_add_file_size_field.py.md
          - Migration Add Used Password Reset Tokens: backend/src/alembic_migrations/versions/20250605_add_used_password_reset_tokens.md
          - Migration Add Used Password Reset Tokens (Python): backend/src/alembic_migrations/versions/20250605_add_used_password_reset_tokens.py.md
      - Backend Tests: backend/tests/README.md
  - Modules:
      - Module Guide: module-guide.md
      - LLM Integration: llm-integration.md
  - Frontend:
      - Frontend Overview: frontend/overview.md
      - Frontend Roadmap: frontend/roadmap.md
      - Frontend Source Directory: frontend/src/README.md
      - Frontend Tests: frontend/tests/README.md
  - Resources:
      - Documentation Enhancements: documentation-enhancements.md
      - _Templates (for contributors)_: _TEMPLATE.md

theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.footer
    - navigation.instant
    - navigation.path
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tabs
    - content.footnotes
    - content.images.lazy
    - content.emoji
    - content.anchors
    - content.action.edit
    - content.action.view
    - content.buttons
    - content.badges
    - content.grid
    - content.cards
    - content.toc
    - content.admonition
    - announce.dismiss
  language: en
  custom_dir: overrides  # For custom 404.html and other overrides

plugins:
  - search
  - awesome-pages
  - mermaid2
  - minify:
      minify_html: true
  # - git-revision-date-localized:  # Disabled due to issues with generated content
  #     fallback_to_build_date: true
  #     exclude:
  #       - backend/src/**
  #       - backend/TEST_LOGGING.md
  #       - backend/TESTING.md
  #       - backend/core/**
  #       - backend/tests/**
  #       - frontend/src/**
  #       - frontend/tests/**
  #       - src/**
  #       - scripts/**
  #       - tests/**
  #       - main.py.md
  #       - "**/*.py.md"
  #     enable_creation_date: false
  # - glightbox  # Temporarily disabled - plugin not installed
  - glightbox
  - macros
  - mkdocstrings:
      handlers:
        python:
          paths: ["../backend/src"]
          options:
            show_root_heading: true
            show_source: true
            docstring_style: google
            merge_init_into_class: true
            show_if_no_docstring: true
            heading_level: 2
            members_order: source

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.magiclink
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  # - pymdownx.tags  # removed due to missing extension, re-add if available in future

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/filip-herceg/ReViewPoint
  analytics:
    provider: plausible
    domain: yourdomain.com  # Replace with your analytics domain
  announce:
    type: info
    text: "🚀 ReViewPoint Docs: Now with enhanced navigation, search, and frontend roadmap!"

edit_uri: https://github.com/filip-herceg/ReViewPoint/edit/main/docs/content/