site_name: ReViewPoint
site_description: Documentation and development manual for ReViewPoint. Modular, scalable, and LLM-powered platform for scientific paper review.
site_author: ReViewPoint Team
site_url: https://github.com/filip-herceg/ReViewPoint

docs_dir: content

nav:
  - Home: index.md
  - Quickstart:
      - Setup Guide: setup.md
      - System Architecture: architecture.md
      - FAQ: faq.md
  - Development:
      - Developer Guidelines: dev-guidelines.md
      - CI/CD: ci-cd.md
      - Changelog: changelog.md
      - Contributing to Documentation: contributing-docs.md
      - How to Use the Docs: how-to-use-docs.md
      - Documentation Enhancements: documentation-enhancements.md
  - Backend:
      - Backend Source Guide: backend-source-guide.md
      - API Reference: api-reference.md
      - Backend API Reference: backend/api-reference.md
      - Backend Models: backend/src/models/README.md
      - Backend Utilities: backend/src/utils/README.md
      - Backend Tests: backend/tests/README.md
  - Modules:
      - Module Guide: module-guide.md
      - LLM Integration: llm-integration.md
  - Frontend:
      - Frontend Overview: frontend/overview.md
      - Frontend Roadmap: frontend/roadmap.md
      - Frontend Source Directory: frontend/src/README.md
      - Frontend Tests: frontend/tests/README.md
  - Resources:
      - Documentation Enhancements: documentation-enhancements.md
      - _Templates (for contributors)_: _TEMPLATE.md

theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.footer
    - navigation.instant
    - navigation.path
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tabs
    - content.footnotes
    - content.images.lazy
    - content.emoji
    - content.anchors
    - content.action.edit
    - content.action.view
    - content.buttons
    - content.badges
    - content.grid
    - content.cards
    - content.toc
    - content.admonition
    - announce.dismiss
  language: en
  custom_dir: overrides  # For custom 404.html and other overrides

plugins:
  - search
  - awesome-pages
  - mermaid2
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox
  - macros
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
            docstring_style: google
            merge_init_into_class: true
          paths: ["../backend/src"]

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.magiclink
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  # - pymdownx.tags  # removed due to missing extension, re-add if available in future

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/filip-herceg/ReViewPoint
  analytics:
    provider: plausible
    domain: yourdomain.com  # Replace with your analytics domain
  announce:
    type: info
    text: "🚀 ReViewPoint Docs: Now with enhanced navigation, search, and frontend roadmap!"

edit_uri: https://github.com/filip-herceg/ReViewPoint/edit/main/docs/content/