version: '3.8'

services:
  postgres_test:
    image: postgres:17-alpine
    container_name: reviewpoint_postgres_test_ci
    environment:
      POSTGRES_DB: reviewpoint_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 30
