name: Build and Publish API Docs

on:
  push:
    paths:
      - 'backend/src/**'
      - 'backend/docs/**'
      - 'backend/pyproject.toml'
      - 'backend/poetry.lock'
      - '.github/workflows/api-docs.yaml'
  pull_request:
    paths:
      - 'backend/src/**'
      - 'backend/docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-api-docs:
    name: Build API Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        working-directory: ./backend
        run: poetry install --no-interaction

      - name: Generate OpenAPI spec
        working-directory: ./backend
        run: |
          poetry run python -c "from fastapi.openapi.utils import get_openapi; from src.main import app; import json; with open('openapi.json', 'w') as f: json.dump(get_openapi(title=app.title, version=app.version, openapi_version=app.openapi_version, description=app.description, routes=app.routes), f)"

      - name: Generate API HTML docs
        run: |
          npm install -g @redocly/cli
          npx redocly build-docs backend/openapi.json -o backend/docs/api-reference.html

      - name: Upload API documentation
        uses: actions/upload-artifact@v3
        with:
          name: api-docs
          path: backend/docs/api-reference.html
