name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Lint, Typecheck & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies (incl. dev)
        run: |
          cd backend
          poetry install --no-root --with dev

      - name: Run Ruff (Lint)
        run: |
          cd backend
          poetry run ruff check .

      - name: Run Black (Format Check)
        run: |
          cd backend
          poetry run black . --check

      - name: Clear Mypy Cache
        run: |
          cd backend
          rm -rf .mypy_cache

      - name: Run Mypy (Typecheck)
        run: |
          cd backend
          poetry run mypy . --config-file mypy.ini

      - name: Run Pytest (Tests)
        run: |
          cd backend
          poetry run pytest --maxfail=1 --disable-warnings --cov=backend --cov-report=xml --cov-report=term

